### ISSUE TITLE
Issues running the container

### ISSUE THREAD

**Issue by roguefalcon** [crazy-max/docker-dokuwiki#1]
The first issue was that it was expecting all the folders (attic, cache, index, locks, etc) in the root folder.  I used the `docker run` command in the README.

The issue that stopped me though is this:
"For security reasons this script will only work with a new and unmodified Dokuwiki installation. You should either re-extract the files from the downloaded package or consult the complete Dokuwiki installation instructions"

I just `git cloned` the repo and ran it with the command you suggested.  I didn't modify any files.

**Comment by crazy-max** [comment]
Can you try with the latest release ?
If you've got any issue, please post your logs here
