### ISSUE TITLE
Missing SQLite & PDO SQLite support (unable to use some plugins)

### ISSUE THREAD

**Issue by regystro** [crazy-max/docker-dokuwiki#21]
#### Steps to reproduce this issue

After a fresh install go to Admin Panel > Extension Manager and install both struct Plugin and sqlite Plugin. Then go to Admin Panel > Additional Plugins > Struct Schema Assignments

#### Expected behaviour

No errors, and plugins working properly.

#### Actual behaviour

Page shows these errors:

- SQLite & PDO SQLite support missing in this PHP install - plugin will not work
- The struct plugin requires the sqlite plugin. Please install and enable it.

---

So please, could you include php7-pdo_sqlite and php7-sqlite3 also?

Thank you!

**Comment by crazy-max** [comment]
@regystro 

> So please, could you include php7-pdo_sqlite and php7-sqlite3 also?

* `php7-sqlite3` is already available.
* `php7-pdo_sqlite` has been added
