### ISSUE TITLE
Latest version  on Raspberry Pi 4 (latest upgrade)

### ISSUE THREAD

**Issue by andymarden** [crazy-max/docker-dokuwiki#39]
I get the following loop in the logs with this:

s6-svscan: warning: unable to iopause: Operation not permitted,
s6-svscan: warning: executing into .s6-svscan/crash,
s6-supervise s6-fdholderd: fatal: unable to iopause: Operation not permitted,
s6-svscan panicked! Dropping to a root shell.,
/bin/sh: can't access tty; job control turned off,
/run/s6/services # ,
s6-svscan: warning: unable to iopause: Operation not permitted,
s6-svscan: warning: executing into .s6-svscan/crash,
s6-supervise s6-fdholderd: fatal: unable to iopause: Operation not permitted,
s6-svscan panicked! Dropping to a root shell.,
/bin/sh: can't access tty; job control turned off,
/run/s6/services # ,
s6-svscan: warning: unable to iopause: Operation not permitted,
s6-supervise s6-fdholderd: fatal: unable to iopause: Operation not permitted,
s6-svscan: warning: executing into .s6-svscan/crash,
s6-svscan panicked! Dropping to a root shell.,
/bin/sh: can't access tty; job control turned off,
/run/s6/services # ,
s6-svscan: warning: unable to iopause: Operation not permitted,
s6-svscan: warning: executing into .s6-svscan/crash,
s6-supervise s6-fdholderd: fatal: unable to iopause: Operation not permitted,
s6-svscan panicked! Dropping to a root shell.,
/bin/sh: can't access tty; job control turned off,
/run/s6/services # ,
s6-svscan: warning: unable to iopause: Operation not permitted,
s6-svscan: warning: executing into .s6-svscan/crash,
s6-svscan panicked! Dropping to a root shell.,
s6-supervise s6-fdholderd: fatal: unable to iopause: Operation not permitted,
/bin/sh: can't access tty; job control turned off,
/run/s6/services # ,
s6-svscan: warning: unable to iopause: Operation not permitted,
s6-svscan: warning: executing into .s6-svscan/crash,
s6-supervise s6-fdholderd: fatal: unable to iopause: Operation not permitted,
s6-svscan panicked! Dropping to a root shell.,
/bin/sh: can't access tty; job control turned off,
/run/s6/services # 

There is some noise around s6 and a bug in Apline 3.13. How do I pull an earlier release (I tried with a version name as per the git repo, but that does not work)

**Comment by andymarden** [comment]
Found out how to get old versions. Going back to edge didn't work by 2018-04-22c works ok

**Comment by crazy-max** [comment]
@andymarden That might help: https://github.com/crazy-max/docker-nextcloud/issues/69#issuecomment-890513830
