### ISSUE TITLE
Sending notification emails?

### ISSUE THREAD

**Issue by gwerbin** [crazy-max/docker-dokuwiki#7]
Hi, thanks for putting this Dockerfile together!

One thing that's apparently lacking is outgoing email notification support. Do you happen to know how that could be added? Unfortunately my own experience level with this stuff ranges from "minimal" to "nonexistent".

It looks like the required steps are something like this:

1. Install and [configure MSMTP to act as a sendmail alternative](https://wiki.alpinelinux.org/wiki/Relay_email_to_gmail_(msmtp,_mailx,_sendmail)), because the Busybox built-in sendmail is very limited
2. Configure PHP to use MSMTP as above, via `sendmail_from` and `sendmail_path` in [php.ini file](https://www.php.net/manual/en/mail.configuration.php).
3. Add the appropriate variables to the Docker-compose file for your send-from address, SMTP account info, etc., and inject them into the Dockerfile where needed.

Does that seem right?

And step 3 this actually need to be done? Or can `php.ini` be safely written in the data directory from the "host side", once the container has been created?

**Comment by crazy-max** [comment]
Hi @gwerbin, I have updated the [compose example](https://github.com/crazy-max/docker-dokuwiki/tree/master/examples/compose) which provides a [simple SMTP relay service](https://github.com/crazy-max/docker-dokuwiki/blob/856e032b895e5977290e19a6999c84d6300bd06d/examples/compose/docker-compose.yml#L21-L28) to be used with Dokuwiki and its [SMTP plugin](https://github.com/crazy-max/docker-dokuwiki#sending-mails-with-smtp).

**Comment by gwerbin** [comment]
Wow, thank you!
